### ISSUE TITLE
Installation error using one_command_install.sh

### ISSUE THREAD

**Issue by miasungeunlee** [Metannotate/Metannotate#74]
Dear author, 
Thank you for developping this great tool ! 
Once metannotate installed using one_command_install.sh, I run 
python2.7 run_metannotate.py -h

And i had this error message below;  do you know where this error comes from ? 

Traceback (most recent call last):
  File "run_metannotate.py", line 7, in <module>
    import tasks
  File "/home/mia/metannotate/tasks.py", line 139, in <module>
    app = celery.Celery('tasks', broker='amqp://', backend='amqp://')
AttributeError: 'module' object has no attribute 'Celery'

Best wishes
Mia

**Comment by jmtsuji** [comment]
@miasungeunlee Thanks for your interest in MetAnnotate!

Unfortunately, MetAnnotate is not being actively updated anymore, so the standard installation in the `master` branch likely will not work. Instead, I recommend to try the docker installation method shown in the `develop` branch: https://github.com/MetAnnotate/MetAnnotate/tree/develop#recommended-docker-installation-for-command-line-and-soon-web-gui  I am not one of the original authors of MetAnnotate, but a colleague and I created that docker container installation to make a portable, stable version of MetAnnotate. It only supports command line usage (not the web UI) and uses RefSeq release 80 (March 2017).

If the Docker installation does not work for you, then a possible alternative tool you could try is [GraftM](https://github.com/geronimp/graftM). GraftM can similarly be used to annotate marker genes from 'omics data.

Hope this helps,
Jackson

**Comment by miasungeunlee** [comment]
Dear Jackson,
Thank you for your comment, it helped a lot :)
Using your docker container installation approach, it installed well and test run worked perfectly.

I would like to use recent version of RefSeq database and i found that one_command_install.sh downloaded recent version of RefSeq database (69G) on our server;  
wget ftp://ftp.ncbi.nlm.nih.gov/refseq/release/complete/complete.nonredundant_protein*.protein.faa.gz

If i replace these files to Refseq.fa and Refseq.fa.ssi into docker container, it will work with no problem? 

Best wishes
Mia

**Comment by jmtsuji** [comment]
@miasungeunlee  I'm glad that you got the docker version to work!

It is a little tricky to use a new version of RefSeq with MetAnnotate, because the format of RefSeq changed. Specifically, sometime in 2017 I think, GI numbers were dropped from RefSeq, and MetAnnotate relied on these GI numbers to function. This is why we version-locked the docker container to use RefSeq release 80.

I believe the author of MetAnnotate recently pushed a minor commit in Bitbucket to work around the GI number issue: https://bitbucket.org/doxeylab/metannotate/commits/19ffcc61b4fb696fc350d81f66511ee87bb94469  I have not tested this, but making this code modification could be one way to use a newer version of RefSeq.

To make use of this possible fix, I recommend re-downloading and installing RefSeq from scratch. Unfortunately, I am not sure what changes MetAnnotate made to the newer RefSeq file you already downloaded before the MetAnnotate installation failed.

You could try the following:
1. Save the [updated version](https://bitbucket.org/doxeylab/metannotate/commits/19ffcc61b4fb696fc350d81f66511ee87bb94469) of `MetAnnotate/scripts/removeFromFasta.pl` to your server (copied below):

```perl
unless (@ARGV)
{	print "usage: perl $0 <list to remove> <fasta>\n";
}

open FILE,$ARGV[0];
while (<FILE>)
{	chomp;
	$_ = ">" . $_;
	$seen{$_} = 1;
}

close FILE;

open FILE,$ARGV[1];
while (<FILE>)
{	chomp;
	if (substr($_,0,1) eq ">")
	{	if ( $seen{$_} )
		{	$print = 0;
	
		}
		else
		{	$print = 1;
			substr($_,0,1) = "";
			@tempsplit = split;
			print ">gi|$tempsplit[0]|ref|$tempsplit[0]| @tempsplit[1 ..$#tempsplit]\n";
		}
	}
	else
	{	if ( $print == 1 )
		{	print;
			print "\n";
		}
	}
	
}
```

Also, save a custom version of the RefSeq installer script (`MetAnnotate/refseq_installation.sh`) to your server. This script is essentially the same as the [version in the develop branch](https://github.com/MetAnnotate/MetAnnotate/blob/develop/refseq_installation.sh), but I changed the URL target to download the most recent version of RefSeq from NCBI instead of downloading release 80:
```bash
#!/bin/bash
set -euxo pipefail

metAnnotateDir="`pwd`"

# Parse user inputs: get the download location if requested
if [ $# == 0 ]; then

    # If no arguments are provided, then assign the default download directory
    output_dir="${metAnnotateDir}/data"
    echo "Installing RefSeq database."
    echo "No user input provided. Will download to the default directory '${output_dir}'."

elif [ $# == 1 ]; then
    input=$1

    if [ $input == "-h" -o $input == "--help" ]; then
        # Provide help info and exit
        echo "${0}: Downloads and indexes RefSeq database for MetAnnotate."
        echo "Usage: ${0} [download_directory]"
        echo "MUST be run within the main MetAnnotate folder."
        echo "If no download_directory is specified, the script will download the database to the 'data' directory within the MetAnnotate folder."
        echo ""
        exit 1
    else
        # Get user-provided output directory
        output_dir=$input
        echo "Installing RefSeq database."
        echo "Downloading to the provided directory '${output_dir}'."
    fi

elif [ $# > 1 ]; then

    echo "ERROR: more than one argument was provided to the script. Try '-h'. Job terminating."
    exit 1

fi

if [ ! `which wget` ]; then
    sudo apt-get -y install wget
fi

cd ${output_dir}
if [ ! -e "Refseq.fa" ] || [ ! -e "Refseq.fa.ssi" ]; then
    echo "Downloading RefSeq database; could take a few hours if connection is slow"
    wget ftp://ftp.ncbi.nlm.nih.gov/refseq/release/complete/complete.nonredundant_protein*.protein.faa.gz
    zcat *.faa.gz >Refseq.fa
    echo "Preprocessing Refseq.fa to removing uncommon amino acids"
    perl ${metAnnotateDir}/scripts/cleanDatabase.pl Refseq.fa > list_to_remove.txt
    perl ${metAnnotateDir}/scripts/removeFromFasta.pl list_to_remove.txt Refseq.fa > Refseq.fixed.fa
    rm list_to_remove.txt
    rm Refseq.fa
    mv Refseq.fixed.fa Refseq.fa
    echo "Preprocessing completes"
    rm *.faa.gz
    esl-sfetch --index Refseq.fa
    echo "Download successful. Saved to ${output_dir}."
else
    echo "Found Refseq.fa and Refseq.fa.ssi in '${output_dir}'. RefSeq is already installed and indexed. Nothing to do."
fi
```

Save both of these scripts as `removeFromFasta.pl` and `refseq_installation.sh` in a directory of your choise.

2. Redo the RefSeq installation from within the docker container:
```
# Set your working directories on your server
database_dir=[ choose the directory where you want to download the database ]
scripts_dir=[ choose the directory where you saved removeFromFasta.pl and refseq_installation.sh ]

# Start the docker container
docker run -v ${database_dir}:/home/linuxbrew/databases \
	-v ${scripts_dir}:/home/linuxbrew/output \
	-it metannotate/metannotate:0.9.2 /bin/bash

# Replace the default scripts with your custom ones
cp output/removeFromFasta.pl MetAnnotate/scripts
cp output/refseq_installation.sh MetAnnotate

# Run the RefSeq installer
cd $METANNOTATE_DIR
ref_UID=$(stat -c "%u" ../databases)
sudo chown -R linuxbrew ../databases
bash refseq_installation.sh /home/linuxbrew/databases
sudo chown -R ${ref_UID} /home/linuxbrew/output
# The 'chown' commands temporarily make the output folder belong to the linuxbrew user inside the Docker container so that the user can run the Docker commands. Files are given back to you at the end.

# Leave the container
exit
```

If everything worked, you should now be able to use the new RefSeq database just like the old one when running the docker version of MetAnnotate.

If you try this somewhat roundabout solution and it works, please let me know. I can potentially update this Github repo to use the modified code and more recent version of RefSeq.

**Comment by miasungeunlee** [comment]
Hi Jackson, 
Thank you a lot for your script, finally it worked but i had some issues... 
First, i had problem of permission when doing zcat (see the error message) 
`refseq_installation.sh: line 47: Refseq.fa: Permission denied `
So, i run manually the script after zcat command. 
And, one of Refseq file was weird (see the error message);
`gzip:  complete.nonredundant_protein.698.protein.faa.gz: invalid compressed data--format violated`
Interestingly, after running cleanDatabase.pl script, the file list_to_remove.txt was empty. Is it normal ? 

Otherwise, once i have Refseq.fa and Refseq.fa.ssi files in databases directory, i run this script, and it worked perfectly :) 
`python2.7 run_metannotate.py --orf_files='data/gene_aa_pH4.5_1.faa,data/gene_aa_pH4.5_2.faa,data/gene_aa_pH4.5_3.faa,data/gene_aa_pH7.5_1.faa,data/gene_aa_pH7.5_2.faa,data/gene_aa_pH7.5_3.faa' --hmm_files='data/hmms/RPOB.HMM' --reference_database='../databases/Refseq.fa' --output_dir='../metagenome_output' --tmp_dir='../output/tmp' --run_mode='sequence' --orfs_hmm_evalue='0.0001' --usearch_percent_id_cutoff='0.4'`

FYI; as i'm new to Docker, first time, i had problem of disk quota; I didn't know that i needed to change Disk image size to 200 GB (in Docker, Resources; Advanced, by default, it is 50 GB)
Thank you again for your help ! 
Best wishes
Mia
